### ISSUE TITLE
Добавить массив картинок и видео.

### ISSUE THREAD

**Issue by Prizrak778** [AnatoliyCh/bot-get-by-link#12]
Тут разве не массив должен быть? Скопом все сразу возвращать.    
Это для всех свойств, кроме text

_Originally posted by @AnatoliyCh in https://github.com/AnatoliyCh/bot-get-by-link/pull/11#discussion_r901093038_

Описание
Свойства ProxyResponseContent должны быть string[], кроме Text.
Создать команду, которая разбивает ответ от прокси, на сообщения для дальнейшей отправки в месенджеры

**Comment by AnatoliyCh** [comment]
Я думаю, лучше вынести в отдельную issue "Добавить команду, которая форматирует вывод"

**Comment by Prizrak778** [comment]
> Я думаю, лучше вынести в отдельную issue "Добавить команду, которая форматирует вывод"

Вынес
