### ISSUE TITLE
Add message builder

### ISSUE THREAD

**Issue by Prizrak778** [AnatoliyCh/bot-get-by-link#29]
- [ ] Check type IFormatterContent (null/IEnum?);
- [ ] Сделать отправку артефактов частями:
https://github.com/AnatoliyCh/bot-get-by-link/blob/e6ac14bf76d780cb4969fe0e642f23777ae2cae3/Bot.GetByLink.Client.Telegram.Polling/Commands/SendMessageCommand.cs#L54
- [ ] Должен добавлять исходный урл в сообщение, отдельным методом

**Comment by AnatoliyCh** [comment]
Добавить в di и пробросить в [TelegramLogger](https://github.com/AnatoliyCh/bot-get-by-link/blob/dev/Bot.GetByLink.Client.Telegram.Common/Model/Logging/TelegramLogger.cs)
