### ISSUE TITLE
Add a common appsetting.json for all projects

### ISSUE THREAD

**Issue by AnatoliyCh** [AnatoliyCh/bot-get-by-link#7]
- основная статья: [Sharing appsettings.json](https://andrewlock.net/sharing-appsettings-json-configuration-files-between-projects-in-asp-net-core/);
- статьи про логирование: [Ведение журнала в .NET](https://docs.microsoft.com/ru-ru/dotnet/core/extensions/logging?tabs=command-line), [Конфигурация и фильтрация логгирования](https://metanit.com/sharp/aspnet5/2.28.php);
- переменные среды: [Использование нескольких сред в ASP.NET Core](https://docs.microsoft.com/ru-ru/aspnet/core/fundamentals/environments?view=aspnetcore-6.0);
- использование [appsettings.{environmentName}.json](https://stackoverflow.com/questions/39573571/net-core-console-application-how-to-configure-appsettings-per-environment).

Как оказалось, webApi не видит добавленный appsettings.json, если он указан как ссылка, поэтому с помощью `ConfigurationBuilder` можно самому прочитать и забиндить (`AddConfiguration`) нужные файлы.

**Comment by Prizrak778** [comment]
В инвокере команд он смотрит на appsettings из Telegram.Polling

**Comment by AnatoliyCh** [comment]
> В инвокере команд он смотрит на appsettings из Telegram.Polling

Ну это и будем исправлять

**Comment by AnatoliyCh** [comment]
> В инвокере команд он смотрит на appsettings из Telegram.Polling

Уже нет, внедрили DI
